from enum import Enum


class TransactionState(str, Enum):
    IDLE = "IDLE"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_AUTHORIZED = "PAYMENT_AUTHORIZED"
    PRODUCT_SELECTED = "PRODUCT_SELECTED"
    DISPENSING = "DISPENSING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"
